language: c++

services:
  - docker

before_install:
  - docker pull thesilverchris/openauto-mazda-build:test
  - docker run -it -d --name build --mount type=bind,source="$(pwd)"/openauto,target=/openauto thesilverchris/openauto-mazda-build:test bash
script:
  - docker exec build cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=/openauto/external/openauto-mazda-build/arm-mazda-linux-musleabi.toolchain /openauto -B/build
  - docker exec build cmake --build /build
