# Run clang-tidy
name: Clang-tidy

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install libusb-1.0-0-dev libssl-dev libboost-test-dev libboost-dev autoconf automake libtool curl make g++ unzip libprotobuf-dev protobuf-compiler lcov libsdbus-c++-dev libsdbus-c++-bin
    - name: Run clang-tidy
      uses: HorstBaerbel/action-clang-tidy@1.1
      # These are optional (defaults displayed)
      with:
        scandir: '.'
        builddir: 'build'
        excludedirs: ''
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
        cmakeoptions: ''
